fix: sorting folders
inspirezonetech/TeachMeCLikeIm5 pull request #82
Opened 2021-11-24 01:11 UTC by ropoko

### 1. This pull request resolves #81 

### 2. Description
The folders name were renamed to resolve the sorting error.

### 3. Fill in checklist by marking [x]

- [x] I've read the CONTRIBUTING.md
- [x] I was assigned to this issue
- [ ] My code is formatted using required linting
- [x] I've run my code locally and checked it works

No code was written.

2021-11-24 22:39 UTC, sabderemane commented
Hi @ropoko , thank you for the suggestion ! I'll suggest also to review the README also because links will be broken after that.

2021-11-24 23:01 UTC, ropoko commented
README fixed!

2021-11-26 15:42 UTC, sabderemane requested changes

2021-11-26 15:42 UTC, sabderemane commented on README.md
> +| Scanf                         | [scanf.c](011-common-built-in-functions/scanf.c)               |
```suggestion
| Scanf                         | [scanf.c](11-common-built-in-functions/scanf.c)               |
```

2021-11-26 16:15 UTC, ropoko commented
sorry, I closed it by accident

2021-11-27 15:54 UTC, sabderemane approved these changes

2021-11-27 15:55 UTC, merged

2021-11-27 15:56 UTC, sabderemane commented
Nevermind, it's good to me I merged!