Hamzabohra patch 2
inspirezonetech/TeachMeCLikeIm5 pull request #88
Opened 2022-10-06 07:48 UTC by hamzabohra

## Please fill in this pull request template before submitting 

### 1. This pull request resolves #70 

### 2. Description
 This tutorial is a very beginner friendly introduction to relational operators in c language. The code is very beginner friendly with easy to understand comments. At the end there is a simple challenge is well

### 3. Fill in checklist by marking [x]

- [x] I've read the CONTRIBUTING.md
- [x] I was assigned to this issue
- [x] My code is formatted using required linting
- [x] I've run my code locally and checked it works

2022-10-06 07:49 UTC, hamzabohra commented
thnx for letting me contribute.

2022-10-08 00:23 UTC, funbeedev requested changes
One minor correction to be made, thanks!

2022-10-08 00:23 UTC, funbeedev commented on 05-operators/relational-operators.c
> +           |  ==      |     x==y    |    x is equals to y                |  10==9 returns true [1]  |
10==9 should return false. Please modify

2022-10-08 06:27 UTC, hamzabohra commented
i have made changes. please check it.
:)

2022-10-09 22:15 UTC, funbeedev approved these changes

2022-10-09 22:15 UTC, funbeedev commented
@hamzabohra  looks good, thanks again :)

2022-10-09 22:16 UTC, merged